version: '2'
services:
  supervisor:
    build:
      context: .
      dockerfile: Dockerfile-supervisor
    volumes:
      - .:/usr/src/app
  
  rabbitmq:
    image: rabbitmq:3.6.5-management 
  

  
