FROM python:3

RUN apt-get update && apt-get install -y supervisor

RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app/
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

CMD ["/usr/bin/supervisord"]
